import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { ArrowLeft, ArrowRight, Eye, LockKeyhole, Mail, UserRound } from 'lucide-react';
import Brand from '../components/ui/Brand';
import Button from '../components/ui/Button';
import { useAuth } from '../hooks/useAuth';

export default function AuthPage({ mode }) {
  const signupMode = mode === 'signup'; const navigate = useNavigate(); const { login, signup } = useAuth();
  const [form, setForm] = useState({ fullName: '', email: '', password: '', confirmPassword: '' }); const [error, setError] = useState(''); const [isSubmitting, setIsSubmitting] = useState(false);
  const change = (event) => setForm((current) => ({ ...current, [event.target.name]: event.target.value }));
  const submit = async (event) => { event.preventDefault(); setError(''); setIsSubmitting(true); try { if (signupMode) await signup(form); else await login({ email: form.email, password: form.password }); navigate('/app/income', { replace: true }); } catch (requestError) { setError(requestError.response?.data?.message || 'Unable to connect. Please try again.'); } finally { setIsSubmitting(false); } };
  return <main className="auth-page"><Link className="back-link" to="/"><ArrowLeft size={18}/> Back to home</Link><div className="auth-shell"><aside className="auth-art"><Brand light /><div><p className="eyebrow">FINANCE, FINELY TUNED</p><h2>Make room for<br/><i>what matters.</i></h2><p>FinTrack brings your financial world into one elegant, reassuring view.</p></div><small>© 2026 FinTrack. Built for a brighter future.</small></aside><section className="auth-card"><div className="auth-heading"><p className="eyebrow">WELCOME {signupMode ? 'TO FINTRACK' : 'BACK'}</p><h1>{signupMode ? 'Create your account' : 'Sign in to your account'}</h1><p>{signupMode ? 'Start making more of every moment.' : 'Pick up right where you left off.'}</p></div><form onSubmit={submit}>{signupMode && <Field name="fullName" value={form.fullName} onChange={change} icon={<UserRound />} label="Full name" placeholder="Enter your full name" />}<Field name="email" value={form.email} onChange={change} icon={<Mail />} label="Email address" placeholder="you@example.com" type="email" /><Field name="password" value={form.password} onChange={change} icon={<LockKeyhole />} label="Password" placeholder="Enter your password" type="password" />{signupMode && <Field name="confirmPassword" value={form.confirmPassword} onChange={change} icon={<LockKeyhole />} label="Confirm password" placeholder="Repeat your password" type="password" />}{!signupMode && <a className="forgot" href="#forgot">Forgot password?</a>}{error && <p className="auth-error" role="alert">{error}</p>}<Button type="submit" className="auth-submit" disabled={isSubmitting}>{isSubmitting ? 'Please wait…' : signupMode ? 'Create account' : 'Sign in'} <ArrowRight size={18} /></Button></form><p className="auth-switch">{signupMode ? 'Already have an account?' : "Don't have an account?"} <Link to={signupMode ? '/login' : '/signup'}>{signupMode ? 'Login' : 'Sign up'}</Link></p></section></div></main>;
}

function Field({ icon, label, ...props }) { return <label className="field"><span>{label}</span><div>{icon}<input required {...props}/>{props.type === 'password' && <Eye size={18}/>}</div></label>; }
